project:
  type: website

website:
  title: Environmental and Demographic Analysis
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-F24/project-01-Uchihas
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
      - text: Dashboard
        href: https://jayantbiradar.shinyapps.io/appp/
        

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
